// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Circle
    {
        [DataMember(Name = "entity_id")]
        public uint EntityId;
        [DataMember(Name = "player_id")]
        public uint PlayerId;
        [DataMember(Name = "direction")]
        public DbVector2 Direction;
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "last_split_time")]
        public SpacetimeDB.Timestamp LastSplitTime;

        public Circle(
            uint EntityId,
            uint PlayerId,
            DbVector2 Direction,
            float Speed,
            SpacetimeDB.Timestamp LastSplitTime
        )
        {
            this.EntityId = EntityId;
            this.PlayerId = PlayerId;
            this.Direction = Direction;
            this.Speed = Speed;
            this.LastSplitTime = LastSplitTime;
        }

        public Circle()
        {
            this.Direction = new();
        }
    }
}
